FROM                            ggtools/java8
MAINTAINER                      pkriens@gmail.com
CMD                             java -jar application.bndrun.jar
ADD                             target/application.bndrun.jar application.bndrun.jar

